config/routes.rb
BookerT::Application.routes.draw do
  resources :profiles

  devise_for :users
  root 'pages#home'
  get "pages/home"
  get "about" => "pages#about"
  get "donate" => "pages#donate"
  get "palette" => "pages#palette"

  

end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "300x300", :thumb => "100x100" }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
         
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
 	end

 	def donate
 	end

 	def palette
 	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render action: 'show', status: :created, location: @profile }
      else
        format.html { render action: 'new' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:Name, :Gender, :Birthdate, :Email, :AboutMe, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
<!-- might need navbar dash static dash top for later -->
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" href="#">BookerT</a> -->
      <%= link_to "BookerT", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
  		<ul class="nav navbar-nav navbar-right">
  		        <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "About", about_path %></li>
  		        <% if user_signed_in? %>
                <li><%= link_to "Account Settings", edit_user_registration_path %></li>
  		          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %>
  		          </li>
  		        <% else %>
  		          <li><%= link_to "Sign in", new_user_session_path %>
  		          </li>
  		        <% end %>
  		</ul>
  	</div> <!-- /.navbar-collapse -->
</div> <!-- /.container -->
</nav>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookerT</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
  

       <%= render 'layouts/header' %>
       <div class="container">
            <% flash.each do |name, msg| %>
              <%= content_tag(:div, msg, class: "alert alert-info") %>
            <% end %>
            <%= yield %>
       </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
       <h2>About BookerT</h2><br>
       
       <p style="font-size:24px">
        First-generation college students at institutions of higher learning often do not receive the support they need to excel (ie. to thrive, not just survive). BookerT aims to address the lack of funding for professional development, unpaid internships, and family emergencies by leveraging the power of  personal networks. Through crowdfunding, we subsidize the cost of items normally prohibitively unaffordable to students with financial need. These items often include professional attire, plane tickets to conferences, rent and groceries for unpaid summer internships, and general family emergency packages for unexpected medical emergencies, evictions, and other serious and personal events.
        <br><br>
         BookerT will augment the impact of existing resources, such as finanical aid offices and scholarship programs, giving college students from lower-income backgrounds the agency necessary to take more control over their academic and extracurricular lives.
       </p>
</div>
<div class="jumbotron">
  <h2>How it Works</h2><br>
  <p style="font-size:24px">
    Students and mentor-donors must create an account and a basic profile, with an attached wishlist, on which the student places screenshots of the items' prices. The student's profile will then be visible to mentor-donors who have signed up and are looking to sponsor a student or students.<br><br>
    In order to sponsor a student, please transfer donations to <b>bookertapp.washington@gmail.com</b> via Square and state the name and email address of the student within the message (as well as any kind words!). To give a general donation, head over to the Donate to the BookerT Fund page.
  </p>
</div>
<div class="jumbotron">
  <h2>The Pilot Program</h2><br>
  <p style="font-size:24px">
    Starting January 2015, we will be launching our pilot program at Georgetown University. Through our application process, we will be selecting six BookerT Scholars to receive money for professional attire and transportation. Over the course of the semester, they will be giving us feedback and blogging about their experience in our program. We will learn and continue building BookerT to cater to more students and more needs.<br><br>
    To apply to be a Scholar, go to: <b>https://docs.google.com/a/georgetown.edu/forms/d/1tGQsIc_FrpbTsEFBoExa3-Nm8yEMcfKtmr7G5S9J7WY/viewform</b>
  </p>
</div>
<div class="jumbotron">
  <h2>Reach out to Us</h2><br>
  <p style="font-size:24px">
    We have a Twitter: <b>@BookerTScholar</b> &nbsp;&nbsp;&nbsp;&nbsp;  
    
<a href="https://twitter.com/BookerTScholar" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @BookerTScholar</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

    <br>
    And an email: <b>bookertapp.washington@gmail.com</b> <br>
    And a Facebook: <b>https://www.facebook.com/bookertscholar</b>
  </p>
</div>

app/views/pages/donate.html.erb
<div class="jumbotron">
       <h1 style="font-size:48px">Donate to the BookerT Fund</h1>
</div>
<div class="jumbotron">
			<h2><b>Step One</b></h2><br>
       <p style="font-size:24px">
       	Sign up with Square at <a href="http://square.com/cash">square.com/cash</a> to enable emailing your donations from your bank account to BookerT!
       </p>
</div>
<div class="jumbotron">
			<h2><b>Step Two</b></h2><br>
				<p style="font-size:24px">
       	Send your donation to <b>bookertapp.washington@gmail.com</b>. CC <b>send@square.com</b> and enter the dollar amount (with dollar sign) in the Subject line. And add a message about how awesome BookerT is, if you'd like!
       	</p>
</div>


app/views/pages/home.html.erb
<div class="jumbotron text-center" style="height: 550px; background-image: url(http://static.panoramio.com/photos/large/20410512.jpg); background-size: 100%;">
     <h1 style="color:white;">Welcome to BookerT! <br>To subscribe to our newsletter, sign up below.</h1>
     <% if user_signed_in? %><br>
        	<%= link_to "Donate to the BookerT Fund", donate_path, class: "btn btn-success btn-lg custom" %>
        	<%= link_to "View Student Profiles", profiles_path, class: "btn btn-warning btn-lg custom" %>
          <%= link_to "Create Profile", new_profile_path, class: "btn btn-primary btn-lg custom" %>
     <% else %><br>
       <p>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
       </p>
  <% end %>  
</div>

<div class="jumbotron text-center" style="background-size: 100%">
  <!-- Begin MailChimp Signup Form -->
  <link href="//cdn-images.mailchimp.com/embedcode/classic-081711.css" rel="stylesheet" type="text/css">
  <style type="text/css">
    #mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
    /* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
       We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
  </style>
  <div id="mc_embed_signup">
  <form action="//herokuapp.us8.list-manage.com/subscribe/post?u=db28e5cb48ce3848ddbae93e6&amp;id=c5d9026bef" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <h2>Also, sign up for newsletters and other updates!</h2><br>
  <div class="mc-field-group">
    <label for="mce-EMAIL">Email Address </label>
    <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
  </div>
  <div class="mc-field-group">
    <label for="mce-FNAME">First Name </label>
    <input type="text" value="" name="FNAME" class="" id="mce-FNAME">
  </div>
  <div class="mc-field-group">
    <label for="mce-LNAME">Last Name </label>
    <input type="text" value="" name="LNAME" class="" id="mce-LNAME">
  </div>
    <div id="mce-responses" class="clear">
      <div class="response" id="mce-error-response" style="display:none"></div>
      <div class="response" id="mce-success-response" style="display:none"></div>
    </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
      <div style="position: absolute; left: -5000px;"><input type="text" name="b_db28e5cb48ce3848ddbae93e6_c5d9026bef" tabindex="-1" value=""></div>
      <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="btn btn-info btn-lg"></div>
  </form>
  </div>
</div>
  <script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
  <!--End mc_embed_signup-->

app/views/pages/palette.html.erb
<div class="jumbotron">
       <h1 style="font-size:48px">View Student Profiles</h1>
</div>
<div class="jumbotron">
			<h2><b>In Progress</b></h2><br>
       <p style="font-size:24px">
       	Entertain yourself at <a href="http://xkcd.com">xkcd.com</a> while we continue building the site!
       </p>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, :html => { :multipart => true } do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :Name %><br>
    <%= f.text_field :Name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :Gender %><br>
    <%= f.text_field :Gender, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :Birthdate %> &nbsp;(MM/DD/YY)<br>
    <%= f.text_field :Birthdate, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :Email %><br>
    <%= f.text_field :Email, class: "form-control" %>
  </div>   
  <div class="form-group">
    <%= f.label :AboutMe, "About Me" %><br>
    <%= f.text_area :AboutMe, class: "form-control" %>
  </div>
  <select class="form-control" style="width:20em">
    <option>Student</option>
    <option>Mentor Only</option>
    <option>Sponsor Only</option>
    <option>Sponsor-Mentor</option>
  </select>
  <span class="help-block">Please indicate what type of user you'll be.<br><br>
  </span> 
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<div id="profiles">
  <% @profiles.each do |profile| %>
    <div class="box" style="font-size:24px">
        <%= image_tag profile.image.url(:medium) %> <br>
        <%= profile.Name %>  &nbsp; <br>
        <%#= profile.Gender %>
        <%#= profile.Birthdate %>
        <%#= profile.Email %>
        <%#= profile.AboutMe %>
        <%#= profile.user.email if profile.user %>
        <%= link_to 'Show', profile %>
        <% if profile.user == current_user %>
          <%= link_to 'Edit', edit_profile_path(profile) %>
          <%= link_to 'Delete', profile, method: :delete, data: { confirm: 'Are you sure?' } %> <br> <br>
      <% end %>
    </div>
  <% end %>
<br>
<%#= link_to 'New Profile', new_profile_path %>
</div>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<%= image_tag @profile.image.url(:medium) %>

<p>
  <strong>Name:</strong>
  <%= @profile.Name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @profile.Gender %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @profile.Birthdate %>
</p>

<p>
  <strong>Email:</strong>
  <%= @profile.Email %>
</p>

<p>
  <strong>Aboutme:</strong>
  <%= @profile.AboutMe %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>